#:schema node_modules/wrangler/config-schema.json
name = "twikoo"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "d28782bf-76b3-4bee-8872-54a390238536"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://pub-dc9a898ff6a14f3e8f2fe0392e47c09d.r2.dev"

[dev]
port = 5000
